language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
 exclude:
  - scala: 2.12.2
    jdk: openjdk6
  - scala: 2.12.2
    jdk: openjdk7
  - scala: 2.12.2
    jdk: oraclejdk7